<?php

/**
 *  @author Martin Matuška <martin@matuska.org>
 *  EN-Revision: Revision of lang_en.inc.php
 */

@define('PLUGIN_KARMA_NAME',		'Karma');
@define('PLUGIN_KARMA_BLAHBLAH',		'Čitatelia hodnotia kvalitu Vašich článkov');
@define('PLUGIN_KARMA_VOTETEXT',		'Hodnotenie tohto článku: ');
@define('PLUGIN_KARMA_VOTETEXT_NAME',		'Správa pri hodnotiacom pruhu');
@define('PLUGIN_KARMA_VOTETEXT_NAME_BLAHBLAH',	'Text použitý při zobrazení pruhu pre hlasovanie.  (Prednastavené: \'' . PLUGIN_KARMA_VOTETEXT . '\')');
@define('PLUGIN_KARMA_RATE',		'Hodnotiť tento článok: %s');
@define('PLUGIN_KARMA_VOTEPOINT_5',		'Veľmi dobrý');
@define('PLUGIN_KARMA_VOTEPOINT_5_NAME',	'Názov najlepšieho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_5_BLAHBLAH',	'Text pre najlepšie hodnotenie. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_5 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_4',		'Dobrý');
@define('PLUGIN_KARMA_VOTEPOINT_4_NAME',	'Názov dobrého hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_4_BLAHBLAH',	'Text dobrého hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_4 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_3',		'Priemer');
@define('PLUGIN_KARMA_VOTEPOINT_3_NAME',	'Názov neutrálneho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_3_BLAHBLAH',	'Text neutrálneho hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_3 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_2',		'Slabý');
@define('PLUGIN_KARMA_VOTEPOINT_2_NAME',	'Názov slabého hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_2_BLAHBLAH',	'Text slabého hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_2 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_1',		'Zlý');
@define('PLUGIN_KARMA_VOTEPOINT_1_NAME',	'Názov najhoršieho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_1_BLAHBLAH',	'Text najhoršieho hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_1 . '\')');
@define('PLUGIN_KARMA_VOTETEXT_5',		'+2');
@define('PLUGIN_KARMA_VOTETEXT_5_NAME',		'Hodnota nejlepšieho hodnotenia');
@define('PLUGIN_KARMA_VOTETEXT_5_BLAHBLAH',	'Text, ktorý sa zobrazí ako hodnota najlepšieho hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_5 . ')');
@define('PLUGIN_KARMA_VOTETEXT_4',		'+1');
@define('PLUGIN_KARMA_VOTETEXT_4_NAME',		'Hodnota dobrého hodnotenia');
@define('PLUGIN_KARMA_VOTETEXT_4_BLAHBLAH',	'Text, ktorý sa zobrazí ako hodnota dobrého hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_4 . ')');
@define('PLUGIN_KARMA_VOTETEXT_3',		'0');
@define('PLUGIN_KARMA_VOTETEXT_3_NAME',		'Hodnota neutrálního hodnocení');
@define('PLUGIN_KARMA_VOTETEXT_3_BLAHBLAH',	'Text, ktorý sa zobrazí ako hodnota neutrálneho hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_3 . ')');
@define('PLUGIN_KARMA_VOTETEXT_2',		'-1');
@define('PLUGIN_KARMA_VOTETEXT_2_NAME',		'Hodnota slabého hodnocení');
@define('PLUGIN_KARMA_VOTETEXT_2_BLAHBLAH',		'Text, ktorý sa zobrazí ako hodnota slabého hodnotenia v hodnotiacompruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_2 . ')');
@define('PLUGIN_KARMA_VOTETEXT_1',		'-2');
@define('PLUGIN_KARMA_VOTETEXT_1_NAME',		'Hodnota nejhoršího hodnocení');
@define('PLUGIN_KARMA_VOTETEXT_1_BLAHBLAH',		'Text, ktorý se zobrazí ako hodnota najhoršieho hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_1 . ')');
@define('PLUGIN_KARMA_VOTED',		'Vaše hodnotenie "%s" bolo zaznamenané.');
@define('PLUGIN_KARMA_VOTES',		'%3$s hlas(ov)');
@define('PLUGIN_KARMA_INVALID',		'Vaše hlasovanie je neplatné.');
@define('PLUGIN_KARMA_ALREADYVOTED',		'Už ste odovzdali Váš hlas.');
@define('PLUGIN_KARMA_NOCOOKIE',		'Váš prehliadač musí podporovať cookies, inak nemôžete hlasovať.');
@define('PLUGIN_KARMA_CLOSED',		'Hodnotenie článku novšie ako %s dní!');
@define('PLUGIN_KARMA_ENTRYTIME',		'Čas pre hodnotenie po zverejnení článku.');
@define('PLUGIN_KARMA_ENTRYTIME_BLAHBLAH',	'Ako dlho (v minútach) po zverejnení článku je povolené jeho neobmedzené hodnotenie? Prednastavené: 1400 (jeden deň)');
@define('PLUGIN_KARMA_VOTINGTIME',		'Čas pre hodnotenie');
@define('PLUGIN_KARMA_VOTINGTIME_BLAHBLAH',		'Ako dlho (v minútach) je potrebné čakať medzi dvoma hodnoteniami. Prednastavené: 5');
@define('PLUGIN_KARMA_TIMEOUT',		'Ochrana pred floodom serveru: Iný čitateľ práve hlasoval. Prosím počkajte s Vaším hlasovaním %s minút.');
@define('PLUGIN_KARMA_CURRENT',		'Aktuálna karma: %2$s, %3$s hlas(ov)');
@define('PLUGIN_KARMA_CURRENT_NAME',		'Správa aktuálneho hodnotenia');
@define('PLUGIN_KARMA_CURRENT_NAME_BLAHBLAH',		'Text použitý pri zobrazení súčasného hodnotenia (%2$s je číselné hodnotenie; %3$s je počet hlasov) (Prednastavené: ' . PLUGIN_KARMA_CURRENT . ')');
@define('PLUGIN_KARMA_EXTENDEDONLY',		'Iba pri celom článku');
@define('PLUGIN_KARMA_EXTENDEDONLY_BLAHBLAH',		'Zobrazovať hodnotenie iba pri zobrazení celého článku (rozšírenej textovej časti).');
@define('PLUGIN_KARMA_MAXKARMA',		'Obdobie pre karmu');
@define('PLUGIN_KARMA_MAXKARMA_BLAHBLAH',		'Zapnúť hlasovanie pre článok, ktorý je mladší ako X dní (Prednastavené: 7)');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VOTES',		'Minimálny počet hlasov na zobrazenie');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VOTES_BLAHBLAH',	'Zobraziť hodnotenie až keď počet hlasov presiahne tu uvedenú hodnotu. Ak chcete zobrazovať hodnotenie vždy, zadajte hodnotu 0.');
@define('PLUGIN_KARMA_LOGGING',		'Logovať hlasy?');
@define('PLUGIN_KARMA_LOGGING_BLAHBLAH',		'Majú byť informácie o hlasovaní logované?');
@define('PLUGIN_KARMA_ACTIVE',		'Zapnúť hlasovanie?');
@define('PLUGIN_KARMA_ACTIVE_BLAHBLAH',		'Je hlasovanie zapnuté?');
//--JAM:@define('PLUGIN_KARMA_ALIGNMENT', 'Voting Bar Alignment');
//--JAM:@define('PLUGIN_KARMA_ALIGNMENT_BLAHBLAH', 'Alignment of voting bar in the entry footer.  Templates can override this setting with !important (Default: right)');
//--JAM: @define('PLUGIN_KARMA_ALIGNMENT_DETECT', 'from style');
@define('PLUGIN_KARMA_VISITS',		'Zapnúť sledovanie návštev?');
@define('PLUGIN_KARMA_VISITS_BLAHBLAH',	'Má byť každé kliknutie na zobrazenie rozšírenej textovej časti počítané a zaznamenávané?');
@define('PLUGIN_KARMA_VISITSCOUNT',		' %4$s zobrazení');
@define('PLUGIN_KARMA_STATISTICS_VISITS_TOP',		'Najčítanejšie články');
@define('PLUGIN_KARMA_STATISTICS_VISITS_BOTTOM',	'Najmenej čítané články');
@define('PLUGIN_KARMA_STATISTICS_VOTES_TOP',		'Články s najviac hlasmi');
@define('PLUGIN_KARMA_STATISTICS_VOTES_BOTTOM',		'Články s najmenej hlasmi');
@define('PLUGIN_KARMA_STATISTICS_POINTS_TOP',		'Články s najlepším hodnotením');
@define('PLUGIN_KARMA_STATISTICS_POINTS_BOTTOM',	'Články s najhorším hodnotením');
@define('PLUGIN_KARMA_STATISTICS_VISITS_NO',		'prečítaní');
@define('PLUGIN_KARMA_STATISTICS_VOTES_NO',		'hlasov');
@define('PLUGIN_KARMA_STATISTICS_POINTS_NO',		'bodov');

@define('PLUGIN_KARMA_STARRATING',		'Zapnúť individuálne hodnotenie článkov?');

@define('PLUGIN_KARMA_VISITS_LOGGEDIN_USERS',		'Sledovať návštevy prihlásených používateľov?');
@define('PLUGIN_KARMA_VISITS_LOGGEDIN_USERS_BLAHBLAH',		'Ak je zapnuté, návštevy prihlásených používateľov sú tiež zaznamenávané. (Medzi týchto používateľov patríte aj vy pri vkladaní nových článkov a ich úprave)');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VISITS',		'Minimálny počet návštev pre zobrazenie');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VISITS_BLAHBLAH',	'Počet návštev bude zobrazený až ked ich počet prekročí tu uvedenú hodnotu. Ak chcete počítadlo zobrazovať vždy, zadajte hodnotu 0.');
@define('PLUGIN_KARMA_WORDRATING',		'Zobrazovať hodnotenie v slovnej forme?');
@define('PLUGIN_KARMA_WORDRATING_BLAHBLAH',		'Chcete zobrazovať hodnotenie ako slová alebo čísla? (Prednastavené: NIE; použiť číselné hodnotenie)');
@define('PLUGIN_KARMA_IMAGE_WITH_MESSAGE',		'Zobrazovať hodnotiacu správu?');
@define('PLUGIN_KARMA_IMAGE_WITH_MESSAGE_BLAHBLAH',		'Zobraziť správu pri hodnotiacom pruhu? (nemá na pruhy žiaden efekt) (Prednastavené: áno)');
@define('PLUGIN_KARMA_IMAGE_WITH_CURR',		'Zobraziť textovú správu spolu s aktuálnym hodnotením?');
@define('PLUGIN_KARMA_IMAGE_WITH_CURR_BLAHBLAH',		'Zobrazovať textové informácie za grafickými pruhmi? (nemá na pruhy žiaden efekt) (Prednastavené: áno)');
@define('PLUGIN_KARMA_IMAGE_WITH_VISITS',		'Zobrazovat text návštev?');
@define('PLUGIN_KARMA_IMAGE_WITH_VISITS_BLAHBLAH',		'Vložiť počet návštěv aj ako text? (za pruhy, nemá na pruhy žiaden efekt) (Prednastavené: áno)');
@define('PLUGIN_KARMA_PREVIEW_BG',		'Pozadie pre tabuľku náhľadu, uvedené nižšie');
@define('PLUGIN_KARMA_PREVIEW_BG_BLAHBLAH',		'Platná je akákoľvek hodnota CSS štýlov; bude použitá ako atribút \'background\' pre tabuľku s náhľadom, a to IBA na administrátorskej stránke. Nemá žiaden efekt na pruhy s hodnotením.');
@define('PLUGIN_KARMA_IMAGE',		'Typ hlasovacích pruhov');
@define('PLUGIN_KARMA_IMAGE_DESC',		'Vyberte súbor s obrázkom (napr. diamonds.png) pre hlasovánie s obrázkami. Vyberte \'' . PLUGIN_KARMA_STATISTICS_POINTS_NO . '\' pre hlasovanie pomocou textu.');
@define('PLUGIN_KARMA_NO_IMAGES',		'V priečinku img/ doplnku karma nie sú žiadne obrázky!');
@define('PLUGIN_KARMA_IMAGE_RATING',		'%1.2f z 5');
@define('PLUGIN_KARMA_IMAGE_INT_RATING',		'%d z 5');
@define('PLUGIN_KARMA_IMAGE_NONE_RATING',		'žiadny');
@define('PLUGIN_KARMA_TAB_OPTIONS',		'Nastavenia');
@define('PLUGIN_KARMA_TAB_APPEARANCE',		'Vzhľad');
@define('PLUGIN_KARMA_TAB_TEXT',		'Text');
@define('PLUGIN_KARMA_DISPLAY_LOG',		'Správa Karmy');
@define('PLUGIN_KARMA_REMOVED_POINTS',		'%s hlasov odstránených z článku %s');
@define('PLUGIN_KARMA_APPROVED_POINTS',		'%s hlasov pre článok %s potvrdených');
@define('PLUGIN_KARMA_POINTS_ERROR',		'Chyba pri aktualizácii hlasov pre článok %s!');
@define('PLUGIN_KARMA_REMOVE_ERROR',		'Chyba pri odstraňovaní hlasov pre článok %s! (Počet bodov bol napriek tomu aktualizovaný.)');
@define('PLUGIN_KARMA_UPDATE_ERROR',		'Zatial žiadne hlasy pre článok %s!');
@define('PLUGIN_KARMA_INVALID_INPUT',		'Nesprávny vstup!');
@define('PLUGIN_KARMA_DELETE_VOTES',		'Vymazať vybrané hlasy');
@define('PLUGIN_KARMA_APPROVE_VOTES',		'Potvrdiť vybrané hlasy');
