<?php

@define('PLUGIN_KARMA_NAME', '文章打分');
@define('PLUGIN_KARMA_BLAHBLAH', '允许访客通过打分的方式评价你的文章质量');
@define('PLUGIN_KARMA_VOTETEXT', '对此文章进行打分: ');
@define('PLUGIN_KARMA_RATE', '对此文章的打分: %s');
@define('PLUGIN_KARMA_VOTEPOINT_5', '非常好');
@define('PLUGIN_KARMA_VOTEPOINT_4', '还不错');
@define('PLUGIN_KARMA_VOTEPOINT_3', '一般般');
@define('PLUGIN_KARMA_VOTEPOINT_2', '没兴趣');
@define('PLUGIN_KARMA_VOTEPOINT_1', '挺糟糕');
@define('PLUGIN_KARMA_VOTED', '你打的分“ %s ”已被保存。');
@define('PLUGIN_KARMA_INVALID', '你的打分无效。');
@define('PLUGIN_KARMA_ALREADYVOTED', '你已经打过分了。');
@define('PLUGIN_KARMA_NOCOOKIE', '你的浏览器必须支持cookies才能对文章进行打分。');
@define('PLUGIN_KARMA_CLOSED', '请对 %s 天内更新的文章进行打分');
@define('PLUGIN_KARMA_ENTRYTIME', '文章发表后允许访客打分的时间');
@define('PLUGIN_KARMA_VOTINGTIME', '打分的时间间隔');
@define('PLUGIN_KARMA_ENTRYTIME_BLAHBLAH', '文章发布多长时间（按分钟计算）以后就允许无限制的打分? 默认: 1440 (一天)');
@define('PLUGIN_KARMA_VOTINGTIME_BLAHBLAH', '每次打分后要间隔多长时间（按分钟计算）以后才能进行下次打分？此设置仅对上述设置“文章发表后允许访客打分的时间”所设置的时间到期后的文章有效。默认: 5');
@define('PLUGIN_KARMA_TIMEOUT', '灌水保护：其它访客刚刚提交了打分，请等待  %s 分钟后再提交你的打分。');
@define('PLUGIN_KARMA_CURRENT', '当前分数: %2$s 。 %3$s 次打分。');
@define('PLUGIN_KARMA_EXTENDEDONLY', '仅限于文章的扩展内容');
@define('PLUGIN_KARMA_EXTENDEDONLY_BLAHBLAH', '仅在文章的扩展内容浏览中打分工具');
@define('PLUGIN_KARMA_MAXKARMA', '允许打分的时限');
@define('PLUGIN_KARMA_MAXKARMA_BLAHBLAH', '只允许对 X 天更新的文章进行打分 (默认：7)');
@define('PLUGIN_KARMA_LOGGING', '记录打分信息');
@define('PLUGIN_KARMA_LOGGING_BLAHBLAH', '是否要记录打分信息？');
@define('PLUGIN_KARMA_ACTIVE', '允许打分');
@define('PLUGIN_KARMA_ACTIVE_BLAHBLAH', '允许对文章打分吗？');
@define('PLUGIN_KARMA_VISITS', '是否跟踪记录访问信息？');
@define('PLUGIN_KARMA_VISITS_BLAHBLAH', '是否把对扩展内容的访问也计算在内并显示出来呢？');
@define('PLUGIN_KARMA_VISITSCOUNT', ' %4$s 次点击');
@define('PLUGIN_KARMA_STATISTICS_VISITS_TOP', '访问次数最多的文章');
@define('PLUGIN_KARMA_STATISTICS_VISITS_BOTTOM', '访问次数最少的文章');
@define('PLUGIN_KARMA_STATISTICS_VOTES_TOP', '总分最高的文章');
@define('PLUGIN_KARMA_STATISTICS_VOTES_BOTTOM', '总分最低的文章');
@define('PLUGIN_KARMA_STATISTICS_POINTS_TOP', '均分最高的文章');
@define('PLUGIN_KARMA_STATISTICS_POINTS_BOTTOM', '均分最低的文章');
@define('PLUGIN_KARMA_STATISTICS_VISITS_NO', '访问');
@define('PLUGIN_KARMA_STATISTICS_VOTES_NO', '次数');
@define('PLUGIN_KARMA_STATISTICS_POINTS_NO', '分数');
@define('PLUGIN_KARMA_STARRATING', '对这篇文章使用单独的打分方式吗？');
