<?php

/**
 *  @author Martin Matu¹ka <martin@matuska.org>
 *  EN-Revision: Revision of lang_en.inc.php
 */

@define('PLUGIN_KARMA_NAME',		'Karma');
@define('PLUGIN_KARMA_BLAHBLAH',		'Èitatelia hodnotia kvalitu Va¹ich èlánkov');
@define('PLUGIN_KARMA_VOTETEXT',		'Hodnotenie tohto èlánku: ');
@define('PLUGIN_KARMA_VOTETEXT_NAME',		'Správa pri hodnotiacom pruhu');
@define('PLUGIN_KARMA_VOTETEXT_NAME_BLAHBLAH',	'Text pou¾itý pøi zobrazení pruhu pre hlasovanie.  (Prednastavené: \'' . PLUGIN_KARMA_VOTETEXT . '\')');
@define('PLUGIN_KARMA_RATE',		'Hodnoti» tento èlánok: %s');
@define('PLUGIN_KARMA_VOTEPOINT_5',		'Veµmi dobrý');
@define('PLUGIN_KARMA_VOTEPOINT_5_NAME',	'Názov najlep¹ieho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_5_BLAHBLAH',	'Text pre najlep¹ie hodnotenie. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_5 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_4',		'Dobrý');
@define('PLUGIN_KARMA_VOTEPOINT_4_NAME',	'Názov dobrého hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_4_BLAHBLAH',	'Text dobrého hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_4 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_3',		'Priemer');
@define('PLUGIN_KARMA_VOTEPOINT_3_NAME',	'Názov neutrálneho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_3_BLAHBLAH',	'Text neutrálneho hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_3 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_2',		'Slabý');
@define('PLUGIN_KARMA_VOTEPOINT_2_NAME',	'Názov slabého hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_2_BLAHBLAH',	'Text slabého hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_2 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_1',		'Zlý');
@define('PLUGIN_KARMA_VOTEPOINT_1_NAME',	'Názov najhor¹ieho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_1_BLAHBLAH',	'Text najhor¹ieho hodnotenia. (Prednastavené: \'' . PLUGIN_KARMA_VOTEPOINT_1 . '\')');
@define('PLUGIN_KARMA_VOTETEXT_5',		'+2');
@define('PLUGIN_KARMA_VOTETEXT_5_NAME',		'Hodnota nejlep¹ieho hodnotenia');
@define('PLUGIN_KARMA_VOTETEXT_5_BLAHBLAH',	'Text, ktorý sa zobrazí ako hodnota najlep¹ieho hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_5 . ')');
@define('PLUGIN_KARMA_VOTETEXT_4',		'+1');
@define('PLUGIN_KARMA_VOTETEXT_4_NAME',		'Hodnota dobrého hodnotenia');
@define('PLUGIN_KARMA_VOTETEXT_4_BLAHBLAH',	'Text, ktorý sa zobrazí ako hodnota dobrého hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_4 . ')');
@define('PLUGIN_KARMA_VOTETEXT_3',		'0');
@define('PLUGIN_KARMA_VOTETEXT_3_NAME',		'Hodnota neutrálního hodnocení');
@define('PLUGIN_KARMA_VOTETEXT_3_BLAHBLAH',	'Text, ktorý sa zobrazí ako hodnota neutrálneho hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_3 . ')');
@define('PLUGIN_KARMA_VOTETEXT_2',		'-1');
@define('PLUGIN_KARMA_VOTETEXT_2_NAME',		'Hodnota slabého hodnocení');
@define('PLUGIN_KARMA_VOTETEXT_2_BLAHBLAH',		'Text, ktorý sa zobrazí ako hodnota slabého hodnotenia v hodnotiacompruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_2 . ')');
@define('PLUGIN_KARMA_VOTETEXT_1',		'-2');
@define('PLUGIN_KARMA_VOTETEXT_1_NAME',		'Hodnota nejhor¹ího hodnocení');
@define('PLUGIN_KARMA_VOTETEXT_1_BLAHBLAH',		'Text, ktorý se zobrazí ako hodnota najhor¹ieho hodnotenia v hodnotiacom pruhu. (Prednastavené: ' . PLUGIN_KARMA_VOTETEXT_1 . ')');
@define('PLUGIN_KARMA_VOTED',		'Va¹e hodnotenie "%s" bolo zaznamenané.');
@define('PLUGIN_KARMA_VOTES',		'%3$s hlas(ov)');
@define('PLUGIN_KARMA_INVALID',		'Va¹e hlasovanie je neplatné.');
@define('PLUGIN_KARMA_ALREADYVOTED',		'U¾ ste odovzdali Vá¹ hlas.');
@define('PLUGIN_KARMA_NOCOOKIE',		'Vá¹ prehliadaè musí podporova» cookies, inak nemô¾ete hlasova».');
@define('PLUGIN_KARMA_CLOSED',		'Hodnotenie èlánku nov¹ie ako %s dní!');
@define('PLUGIN_KARMA_ENTRYTIME',		'Èas pre hodnotenie po zverejnení èlánku.');
@define('PLUGIN_KARMA_ENTRYTIME_BLAHBLAH',	'Ako dlho (v minútach) po zverejnení èlánku je povolené jeho neobmedzené hodnotenie? Prednastavené: 1400 (jeden deò)');
@define('PLUGIN_KARMA_VOTINGTIME',		'Èas pre hodnotenie');
@define('PLUGIN_KARMA_VOTINGTIME_BLAHBLAH',		'Ako dlho (v minútach) je potrebné èaka» medzi dvoma hodnoteniami. Prednastavené: 5');
@define('PLUGIN_KARMA_TIMEOUT',		'Ochrana pred floodom serveru: Iný èitateµ práve hlasoval. Prosím poèkajte s Va¹ím hlasovaním %s minút.');
@define('PLUGIN_KARMA_CURRENT',		'Aktuálna karma: %2$s, %3$s hlas(ov)');
@define('PLUGIN_KARMA_CURRENT_NAME',		'Správa aktuálneho hodnotenia');
@define('PLUGIN_KARMA_CURRENT_NAME_BLAHBLAH',		'Text pou¾itý pri zobrazení súèasného hodnotenia (%2$s je èíselné hodnotenie; %3$s je poèet hlasov) (Prednastavené: ' . PLUGIN_KARMA_CURRENT . ')');
@define('PLUGIN_KARMA_EXTENDEDONLY',		'Iba pri celom èlánku');
@define('PLUGIN_KARMA_EXTENDEDONLY_BLAHBLAH',		'Zobrazova» hodnotenie iba pri zobrazení celého èlánku (roz¹írenej textovej èasti).');
@define('PLUGIN_KARMA_MAXKARMA',		'Obdobie pre karmu');
@define('PLUGIN_KARMA_MAXKARMA_BLAHBLAH',		'Zapnú» hlasovanie pre èlánok, ktorý je mlad¹í ako X dní (Prednastavené: 7)');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VOTES',		'Minimálny poèet hlasov na zobrazenie');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VOTES_BLAHBLAH',	'Zobrazi» hodnotenie a¾ keï poèet hlasov presiahne tu uvedenú hodnotu. Ak chcete zobrazova» hodnotenie v¾dy, zadajte hodnotu 0.');
@define('PLUGIN_KARMA_LOGGING',		'Logova» hlasy?');
@define('PLUGIN_KARMA_LOGGING_BLAHBLAH',		'Majú by» informácie o hlasovaní logované?');
@define('PLUGIN_KARMA_ACTIVE',		'Zapnú» hlasovanie?');
@define('PLUGIN_KARMA_ACTIVE_BLAHBLAH',		'Je hlasovanie zapnuté?');
//--JAM:@define('PLUGIN_KARMA_ALIGNMENT', 'Voting Bar Alignment');
//--JAM:@define('PLUGIN_KARMA_ALIGNMENT_BLAHBLAH', 'Alignment of voting bar in the entry footer.  Templates can override this setting with !important (Default: right)');
//--JAM: @define('PLUGIN_KARMA_ALIGNMENT_DETECT', 'from style');
@define('PLUGIN_KARMA_VISITS',		'Zapnú» sledovanie náv¹tev?');
@define('PLUGIN_KARMA_VISITS_BLAHBLAH',	'Má by» ka¾dé kliknutie na zobrazenie roz¹írenej textovej èasti poèítané a zaznamenávané?');
@define('PLUGIN_KARMA_VISITSCOUNT',		' %4$s zobrazení');
@define('PLUGIN_KARMA_STATISTICS_VISITS_TOP',		'Najèítanej¹ie èlánky');
@define('PLUGIN_KARMA_STATISTICS_VISITS_BOTTOM',	'Najmenej èítané èlánky');
@define('PLUGIN_KARMA_STATISTICS_VOTES_TOP',		'Èlánky s najviac hlasmi');
@define('PLUGIN_KARMA_STATISTICS_VOTES_BOTTOM',		'Èlánky s najmenej hlasmi');
@define('PLUGIN_KARMA_STATISTICS_POINTS_TOP',		'Èlánky s najlep¹ím hodnotením');
@define('PLUGIN_KARMA_STATISTICS_POINTS_BOTTOM',	'Èlánky s najhor¹ím hodnotením');
@define('PLUGIN_KARMA_STATISTICS_VISITS_NO',		'preèítaní');
@define('PLUGIN_KARMA_STATISTICS_VOTES_NO',		'hlasov');
@define('PLUGIN_KARMA_STATISTICS_POINTS_NO',		'bodov');

@define('PLUGIN_KARMA_STARRATING',		'Zapnú» individuálne hodnotenie èlánkov?');

@define('PLUGIN_KARMA_VISITS_LOGGEDIN_USERS',		'Sledova» náv¹tevy prihlásených pou¾ívateµov?');
@define('PLUGIN_KARMA_VISITS_LOGGEDIN_USERS_BLAHBLAH',		'Ak je zapnuté, náv¹tevy prihlásených pou¾ívateµov sú tie¾ zaznamenávané. (Medzi týchto pou¾ívateµov patríte aj vy pri vkladaní nových èlánkov a ich úprave)');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VISITS',		'Minimálny poèet náv¹tev pre zobrazenie');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VISITS_BLAHBLAH',	'Poèet náv¹tev bude zobrazený a¾ ked ich poèet prekroèí tu uvedenú hodnotu. Ak chcete poèítadlo zobrazova» v¾dy, zadajte hodnotu 0.');
@define('PLUGIN_KARMA_WORDRATING',		'Zobrazova» hodnotenie v slovnej forme?');
@define('PLUGIN_KARMA_WORDRATING_BLAHBLAH',		'Chcete zobrazova» hodnotenie ako slová alebo èísla? (Prednastavené: NIE; pou¾i» èíselné hodnotenie)');
@define('PLUGIN_KARMA_IMAGE_WITH_MESSAGE',		'Zobrazova» hodnotiacu správu?');
@define('PLUGIN_KARMA_IMAGE_WITH_MESSAGE_BLAHBLAH',		'Zobrazi» správu pri hodnotiacom pruhu? (nemá na pruhy ¾iaden efekt) (Prednastavené: áno)');
@define('PLUGIN_KARMA_IMAGE_WITH_CURR',		'Zobrazi» textovú správu spolu s aktuálnym hodnotením?');
@define('PLUGIN_KARMA_IMAGE_WITH_CURR_BLAHBLAH',		'Zobrazova» textové informácie za grafickými pruhmi? (nemá na pruhy ¾iaden efekt) (Prednastavené: áno)');
@define('PLUGIN_KARMA_IMAGE_WITH_VISITS',		'Zobrazovat text náv¹tev?');
@define('PLUGIN_KARMA_IMAGE_WITH_VISITS_BLAHBLAH',		'Vlo¾i» poèet náv¹tìv aj ako text? (za pruhy, nemá na pruhy ¾iaden efekt) (Prednastavené: áno)');
@define('PLUGIN_KARMA_PREVIEW_BG',		'Pozadie pre tabuµku náhµadu, uvedené ni¾¹ie');
@define('PLUGIN_KARMA_PREVIEW_BG_BLAHBLAH',		'Platná je akákoµvek hodnota CSS ¹týlov; bude pou¾itá ako atribút \'background\' pre tabuµku s náhµadom, a to IBA na administrátorskej stránke. Nemá ¾iaden efekt na pruhy s hodnotením.');
@define('PLUGIN_KARMA_IMAGE',		'Typ hlasovacích pruhov');
@define('PLUGIN_KARMA_IMAGE_DESC',		'Vyberte súbor s obrázkom (napr. diamonds.png) pre hlasovánie s obrázkami. Vyberte \'' . PLUGIN_KARMA_STATISTICS_POINTS_NO . '\' pre hlasovanie pomocou textu.');
@define('PLUGIN_KARMA_NO_IMAGES',		'V prieèinku img/ doplnku karma nie sú ¾iadne obrázky!');
@define('PLUGIN_KARMA_IMAGE_RATING',		'%1.2f z 5');
@define('PLUGIN_KARMA_IMAGE_INT_RATING',		'%d z 5');
@define('PLUGIN_KARMA_IMAGE_NONE_RATING',		'¾iadny');
@define('PLUGIN_KARMA_TAB_OPTIONS',		'Nastavenia');
@define('PLUGIN_KARMA_TAB_APPEARANCE',		'Vzhµad');
@define('PLUGIN_KARMA_TAB_TEXT',		'Text');
@define('PLUGIN_KARMA_DISPLAY_LOG',		'Správa Karmy');
@define('PLUGIN_KARMA_REMOVED_POINTS',		'%s hlasov odstránených z èlánku %s');
@define('PLUGIN_KARMA_APPROVED_POINTS',		'%s hlasov pre èlánok %s potvrdených');
@define('PLUGIN_KARMA_POINTS_ERROR',		'Chyba pri aktualizácii hlasov pre èlánok %s!');
@define('PLUGIN_KARMA_REMOVE_ERROR',		'Chyba pri odstraòovaní hlasov pre èlánok %s! (Poèet bodov bol napriek tomu aktualizovaný.)');
@define('PLUGIN_KARMA_UPDATE_ERROR',		'Zatial ¾iadne hlasy pre èlánok %s!');
@define('PLUGIN_KARMA_INVALID_INPUT',		'Nesprávny vstup!');
@define('PLUGIN_KARMA_DELETE_VOTES',		'Vymaza» vybrané hlasy');
@define('PLUGIN_KARMA_APPROVE_VOTES',		'Potvrdi» vybrané hlasy');
