<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'voku\\cache\\' => array($vendorDir . '/voku/simple-cache/src/voku/cache'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Laminas\\ZendFrameworkBridge\\' => array($vendorDir . '/laminas/laminas-zendframework-bridge/src'),
    'Laminas\\Stdlib\\' => array($vendorDir . '/laminas/laminas-stdlib/src'),
    'Laminas\\Db\\' => array($vendorDir . '/laminas/laminas-db/src'),
    'Katzgrau\\KLogger\\' => array($vendorDir . '/katzgrau/klogger/src'),
);
