<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'voku\\cache\\' => array($vendorDir . '/voku/simple-cache/src/voku/cache'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Smarty\\' => array($vendorDir . '/smarty/smarty/src'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Masterminds\\' => array($vendorDir . '/masterminds/html5/src'),
    'Katzgrau\\KLogger\\' => array($vendorDir . '/katzgrau/klogger/src'),
);
