<?php return array(
    'root' => array(
        'name' => 's9y/serendipity',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '3a6e8fedc829152ea82abf2c4b2d8e157090dfbb',
        'type' => 's9y-core',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'katzgrau/klogger' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '36481c69db9305169a2ceadead25c2acaabd567c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../katzgrau/klogger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.9.0',
            'version' => '2.9.0.0',
            'reference' => 'f5ac2c0b0a2eefca70b2ce32a5809992227e75a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mf2/mf2' => array(
            'pretty_version' => 'v0.5.0',
            'version' => '0.5.0.0',
            'reference' => 'ddc56de6be62ed4a21f569de9b80e17af678ca50',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mf2/mf2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/http_request2' => array(
            'pretty_version' => 'v2.7.0',
            'version' => '2.7.0.0',
            'reference' => 'b1c61b71128045734d757c4d3d436457ace80ea7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/http_request2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_dns2' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'reference' => 'c4a167ff1bc93aaae95601ebc86099376c994581',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_dns2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php81_bc/strftime' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'reference' => '4c1b56eaae4bb3f02f994ba47c2e5a225378e62f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php81_bc/strftime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        's9y/serendipity' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '3a6e8fedc829152ea82abf2c4b2d8e157090dfbb',
            'type' => 's9y-core',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'smarty/smarty' => array(
            'pretty_version' => 'v5.4.3',
            'version' => '5.4.3.0',
            'reference' => 'c6bff5795081ca5e60aabda59fb87daa511acd1e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '85181ba99b2345b0ef10ce42ecac37612d9fd341',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/simple-cache' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => 'd6578b2b1c7a1ed36c4a862cae826b703520e73b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
