<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => 'eee050e26daa50be1034fb6ff29e79d130280ceb',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => 'eee050e26daa50be1034fb6ff29e79d130280ceb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'katzgrau/klogger' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '46cdd92a9b4a8443120cc955bf831450cb274813',
            'type' => 'library',
            'install_path' => __DIR__ . '/../katzgrau/klogger',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/http_request2' => array(
            'pretty_version' => 'v2.6.0',
            'version' => '2.6.0.0',
            'reference' => 'f010a16ccddd1ee7d2ee085e8006ee712c00f706',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/http_request2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_dns2' => array(
            'pretty_version' => 'v1.5.4',
            'version' => '1.5.4.0',
            'reference' => 'c4a167ff1bc93aaae95601ebc86099376c994581',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_dns2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/net_url2' => array(
            'pretty_version' => 'v2.2.2',
            'version' => '2.2.2.0',
            'reference' => '07fd055820dbf466ee3990abe96d0e40a8791f9d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/net_url2',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php81_bc/strftime' => array(
            'pretty_version' => '0.5.0',
            'version' => '0.5.0.0',
            'reference' => '4c1b56eaae4bb3f02f994ba47c2e5a225378e62f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php81_bc/strftime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'fe0936ee26643249e916849d48e3a51d5f5e278b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'smarty/smarty' => array(
            'pretty_version' => 'v4.3.4',
            'version' => '4.3.4.0',
            'reference' => '3931d8f54b8f7a4ffab538582d34d4397ba8daa5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../smarty/smarty',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'voku/simple-cache' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => 'd6578b2b1c7a1ed36c4a862cae826b703520e73b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../voku/simple-cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
